# Generated by Django 4.1 on 2023-08-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='desc',
            field=models.TextField(),
        ),
    ]
