# Generated by Django 4.1 on 2023-08-24 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_notes_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='desc',
            new_name='text',
        ),
    ]
