# Generated by Django 4.1 on 2023-06-12 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imaage',
            new_name='Image',
        ),
    ]
